### ISSUE TITLE
error

### ISSUE THREAD

**Issue by anso3000** [Miei/battle-notify#1]
[proxy] preloading modules

[proxy] failed to load "battle-notify-master"
Error: Cannot find module 'slash'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\xxx\Desktop\tera-proxy\bin\node_modules\battle-notify-master\index.js:1:77)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by wuaw** [comment]
https://github.com/baldera-mods/slash

Slash is another module, found at the link above.

I'll probably just remove the dependency for now, I was only using it for debugging purposes anyway.
